### ISSUE TITLE
Kernel message writer

### ISSUE THREAD

**Issue by ivoribeiro** [Infinity-OS/infinity#35]
Module to print several types of messages with beautiful colors.

Examples:

- kprint("success","The kernel was loaded")
- kprint("error","Failed to load memory manager")
- kprint("info","A context has been switched")
- kprint("warning","Low memory")
- kprint("info","A context has been switched")

**Comment by gil0mendes** [comment]
That can be interesting for some situations. I have a suggestion, the first argument could be an Enum instead of a string literal. Something like:

```rust
kprint(MsgType::Success, "The success message goes here!");
```

This way can avoid lots of errors, because we can mitigate it at compile time.

**Comment by ivoribeiro** [comment]
@gil0mendes Done :+1:
